"""The document read back out of state, as a scene that can reopen it.

A config goes one way in: a ``Scene`` is seeded into state, key by key, and
from then on state is what the app is showing. Saving is that walk run
backwards over the same map, which is what keeps the two from drifting into
describing different apps -- and what makes the round trip a thing a test can
check rather than a thing to be careful about.

What is *not* in state, and never was, is which files to read. That is carried
over from the scene the session was built on rather than reconstructed from the
objects it loaded.
"""

# Third Party
import tomlkit as tk

# Internal
from . import registry
from .logic.capture import VIEWPORTS
from .scene import Scene
from .state import ObjectState, screenshot_viewport


def _place(data: dict, path: str, value) -> None:
    """Write ``value`` at the dotted ``path``, making the branches it needs."""
    *branches, leaf = path.split(".")
    for branch in branches:
        data = data.setdefault(branch, {})
    data[leaf] = value


def _entries(scene: Scene, data: dict):
    """Each renderable beside its own entry in the dumped scene."""
    for group in ("meshes", "volumes", "segmentations"):
        yield from zip(getattr(scene, group), data.get(group, []))


def scene_from_state(state, scene: Scene) -> Scene:
    """The scene as it now stands: what was loaded, showing what is shown."""
    data = scene.model_dump(mode="json", exclude_none=True)

    for key in registry.keys_in_scope(registry.Scope.DOCUMENT):
        _place(data, registry.source_of(key), registry.to_config(key, state[key]))

    data["screenshot_viewports"] = [
        viewport for viewport in VIEWPORTS if state[screenshot_viewport(viewport)]
    ]

    for obj, entry in _entries(scene, data):
        keys = ObjectState.of(obj)
        for prop, field in registry.OBJECT_SOURCES.items():
            if field in type(obj).model_fields:
                entry[field] = state[getattr(keys, prop)]

        # The three range sliders are one field: a crop is a box, and the axes
        # are only split up because that is how it is dragged.
        entry["crop"] = [bound for key in keys.clip_bounds for bound in state[key]]

    return Scene(**data)


def _ordered(data: dict) -> dict:
    """The same mapping, with every scalar ahead of every table.

    TOML reads a bare key as belonging to the table above it, so a scalar
    written after one would come back meaning something else.
    """

    def table(value) -> bool:
        return isinstance(value, dict) or (
            isinstance(value, list) and any(isinstance(item, dict) for item in value)
        )

    scalars = {key: value for key, value in data.items() if not table(value)}
    tables = {key: value for key, value in data.items() if table(value)}
    return {
        **scalars,
        **{
            key: _ordered(value) if isinstance(value, dict) else value
            for key, value in tables.items()
        },
    }


def to_toml(scene: Scene) -> str:
    """``scene`` as a config file -- the same one ``--config`` reads."""
    from . import __version__

    data = _ordered(scene.model_dump(mode="json", exclude_none=True))
    return f"# Generated by cardio version {__version__}\n\n" + tk.dumps(data)
