"""The action log as a file that asks for it all again.

A script is the console's own lines under a prefix. ``format_call`` writes
both, so the two cannot drift into different languages: what the panel showed
is what the file holds, and ``do.`` is the whole of the difference.

The proxy is what makes that true. ``do.add_rotation(axis='Z')`` is not a
translation of ``add_rotation(axis='Z')`` into some scripting API -- it is that
line, asked of a ``Session`` rather than of a browser.
"""

# System
import datetime as dt
import functools as ft
import pathlib as pl

# Internal
from . import toml
from .console import format_call

# What the generated file binds its session to, and so what every line in it
# is written against.
PROXY = "do"

# The one action a script has no use for. Every other line puts the app
# somewhere; this one takes the app away, and a script ends by ending.
UNSCRIPTED = frozenset({"close_application"})

RECORDED_FORMAT = "%Y-%m-%d %H:%M:%S"


class Actions:
    """Every action a session has, as something to call by name.

    The attribute is the action's name, so that a line of a script and a line
    of the console differ by the prefix alone. A name that is not an action is
    refused here rather than at the call, and says what there is instead.
    """

    def __init__(self, session):
        self.session = session

    def __getattr__(self, name: str):
        # Only reached for what the instance does not have, so ``session``
        # answers for itself and never arrives here.
        session = self.__dict__["session"]
        if name not in session.actions.names:
            raise AttributeError(
                f"No such action: {name!r}. Known: {', '.join(session.actions.names)}"
            )
        return ft.partial(session.do, name)


def script(config=None, *, server=None, **overrides) -> Actions:
    """A session on ``config``, as something to ask for actions by name.

    What a generated script calls, and the shortest way to drive the app from
    python. ``do.session`` is the way to everything a session does that is not
    an action -- saving it out, or reading its state.
    """
    # Deferred: a session composes the logic, and the logic's console writes
    # the scripts this module renders. Importing it up here would be circular.
    from .session import Session

    return Actions(Session.from_config(config, server=server, **overrides))


def render(
    actions,
    config: str,
    recorded: dt.datetime | None = None,
    dropped: int = 0,
) -> str:
    """``actions`` as a python file that runs them against ``config``.

    ``config`` is named relative to the script rather than absolutely: the two
    are written together and are meant to travel together, and a script should
    run from whatever directory it is run from.
    """
    # Deferred: cardio/__init__ imports this module, so a module-scope import
    # here would be circular. The same reason toml.dumps defers it.
    from . import __version__

    recorded = recorded or dt.datetime.now().astimezone()

    lines = [
        "#!/usr/bin/env python",
        f"# Generated by cardio version {__version__}",
        f'"""Recorded {recorded.strftime(RECORDED_FORMAT)}."""',
        "",
        "# System",
        "import pathlib as pl",
        "",
        "# Third Party",
        "import cardio",
        "",
        f"{PROXY} = cardio.script(pl.Path(__file__).parent / {config!r})",
        "",
    ]

    if dropped:
        lines += [
            f"# The log no longer held its first {dropped} lines, so this script",
            "# does not start the app where the session started.",
            "",
        ]

    lines += [
        format_call(name, arguments, prefix=f"{PROXY}.")
        for name, arguments in actions
        if name not in UNSCRIPTED
    ]

    return "\n".join(lines) + "\n"


def save(
    directory,
    stem: str,
    actions,
    opened_as: str,
    recorded: dt.datetime | None = None,
    dropped: int = 0,
) -> pl.Path:
    """Write the script and the scene it opens, and say where the script went.

    Two files named for the same moment, so that a directory of them reads as
    a list of sessions rather than as a pile of halves.
    """
    directory = pl.Path(directory)
    config = f"{stem}.toml"

    # ``toml.write`` is the app's one "write this text, making the directory it
    # needs". The script is not TOML; the writing is the same.
    toml.write(directory / config, opened_as)
    return toml.write(
        directory / f"{stem}.py", render(actions, config, recorded, dropped)
    )
