"""Writing one of the app's TOML files.

A rotation sequence and a saved session are different documents that are
written the same way: the banner saying which version wrote them, then the
model as TOML. Both used to spell that out, so the banner existed twice.
"""

# System
import pathlib as pl

# Third Party
import tomlkit as tk


def dumps(data: dict) -> str:
    """``data`` as a cardio TOML file, under the banner they all carry."""
    # Deferred: cardio/__init__ imports the modules that call this, so a
    # module-scope import here would be circular.
    from . import __version__

    return f"# Generated by cardio version {__version__}\n\n" + tk.dumps(data)


def write(path, text: str) -> pl.Path:
    """Write ``text`` to ``path``, making the directory it needs first."""
    path = pl.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
