name = "Cardiac CT"
description = "Cardiac"

# Lighting parameters
ambient = 0.4
diffuse = 0.6
specular = 0.2

[[transfer_functions]]
window = 571
level = 189
locolor = [1.0, 1.0, 1.0]
hicolor = [1.0, 1.0, 1.0]
opacity = 0.05
shape = "rightskew"

[[transfer_functions]]
window = 202
level = 218
locolor = [1.0, 0.0, 0.0]
hicolor = [1.0, 1.0, 0.0]
opacity = 0.87
shape = "rightskew"