name = "Lung"
description = "Lung"

# Lighting parameters
ambient = 0.0
diffuse = 1.0
specular = 0.0

# Transfer function pair
[[transfer_functions]]

# Opacity transfer function - constant opacity of 1.0
[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = -1350.0
y = 1.0

[[transfer_functions.opacity.points]]
x = 3071.0
y = 1.0

# Color transfer function - black to white across window
[transfer_functions.color]
[[transfer_functions.color.points]]
x = -1350.0
r = 0.0
g = 0.0
b = 0.0

[[transfer_functions.color.points]]
x = 150.0
r = 1.0
g = 1.0
b = 1.0

[[transfer_functions.color.points]]
x = 3071.0
r = 1.0
g = 1.0
b = 1.0
