# Transfer function presets for volume rendering
# Users can reference these by name in their config files

[cardiac]
name = "Cardiac CT"
description = "Two-component transfer function for cardiac CT data"

[[cardiac.transfer_functions]]
window = 571
level = 189
locolor = [1.0, 1.0, 1.0]
hicolor = [1.0, 1.0, 1.0]
opacity = 0.05
shape = "rightskew"

[[cardiac.transfer_functions]]
window = 202
level = 218
locolor = [1.0, 0.0, 0.0]
hicolor = [1.0, 1.0, 0.0]
opacity = 0.87
shape = "rightskew"

[bone]
name = "Bone"
description = "Single transfer function optimized for bone visualization"

[[bone.transfer_functions]]
window = 1000
level = 400
locolor = [1.0, 1.0, 0.9]
hicolor = [1.0, 1.0, 1.0]
opacity = 0.8
shape = "rightskew"

[soft_tissue]
name = "Soft Tissue"
description = "Transfer function for soft tissue visualization"

[[soft_tissue.transfer_functions]]
window = 350
level = 50
locolor = [0.8, 0.6, 0.4]
hicolor = [1.0, 0.8, 0.6]
opacity = 0.6
shape = "rightskew"

[vessels]
name = "Vessels"
description = "Transfer function optimized for vascular structures"

[[vessels.transfer_functions]]
window = 400
level = 150
locolor = [0.0, 0.0, 1.0]
hicolor = [0.0, 1.0, 1.0]
opacity = 0.9
shape = "rightskew"