name = "Vascular_Open"
description = "Vascular (Open)"

ambient = 0.7
diffuse = 0.4
specular = 1.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = -96.5
y = 0.0

[[transfer_functions.opacity.points]]
x = 269.0
y = 0.05

[[transfer_functions.opacity.points]]
x = 474.5
y = 0.0

[transfer_functions.color]
[[transfer_functions.color.points]]
x = -96.5
color = [1.0, 1.0, 1.0]

[[transfer_functions.color.points]]
x = 474.5
color = [1.0, 1.0, 1.0]

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = 117
y = 0.0

[[transfer_functions.opacity.points]]
x = 246.0
y = 0.87

[[transfer_functions.opacity.points]]
x = 319
y = 0.0

[transfer_functions.color]
[[transfer_functions.color.points]]
x = 117
color = [1.0, 0.0, 0.0]

[[transfer_functions.color.points]]
x = 319
color = [1.0, 1.0, 0.0]
