name = "Radiograph"
description = "Radiograph"

ambient = 1.0
diffuse = 1.0
specular = 0.0

[[transfer_functions]]

[transfer_functions.opacity]
[[transfer_functions.opacity.points]]
x = -1024.0
y = 0.0

[[transfer_functions.opacity.points]]
x = -200.0
y = 0.0

[[transfer_functions.opacity.points]]
x = 300.0
y = 0.01

[[transfer_functions.opacity.points]]
x = 3071.0
y = 0.01

[transfer_functions.color]
[[transfer_functions.color.points]]
x = -1024.0
color = [0.0, 0.0, 0.0]

[[transfer_functions.color.points]]
x = -200.0
color = [0.0, 0.0, 0.0]

[[transfer_functions.color.points]]
x = 300.0
color = [1.0, 1.0, 1.0]

[[transfer_functions.color.points]]
x = 3071.0
color = [1.0, 1.0, 1.0]
